; ============================================================
;  PlatformIO 项目配置 — ESP32-S3-N16R8
; ============================================================
[platformio]
default_envs = production
; set the default environment to wifi_scan_debug for testing Wi-Fi scanning functionality. You can switch to esp32s3 for normal operation.

[env:production]
platform  = espressif32
board     = 4d_systems_esp32s3_gen4_r8n16
framework = espidf

; Flash & PSRAM: N16R8 = 16MB Flash + 8MB PSRAM (OPI)
board_build.flash_mode      = dio
board_build.flash_size      = 16MB
board_build.partitions      = partitions_16MB.csv

monitor_speed = 115200
upload_speed  = 921600

[env:wifi_scan_debug]
platform  = espressif32
board     = 4d_systems_esp32s3_gen4_r8n16
framework = espidf

board_build.flash_mode      = dio
board_build.flash_size      = 16MB
board_build.partitions      = partitions_16MB.csv

monitor_speed = 115200
upload_speed  = 921600
